# Generated by Django 5.1.7 on 2025-03-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reciver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reciver_user', to='bottle.user'),
        ),
    ]
